server:
  port: 8020
spring:
  application:
    name: config-client
  cloud:
    config:
      ### config配置文件规则中的application,若不配置此项,则默认使用spring.application.name
      name: config
      profile: dev
      label: master